name: share_box
description: A new Flutter project.


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
#追加した分
  get: ^4.1.4
  dots_indicator: ^2.1.0

  cupertino_icons: ^1.0.2
  share_plus: ^3.1.0
  flutter_secure_storage: ^5.0.2
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  google_sign_in: ^5.2.4
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true



#追加した分
  assets:
    - assets/image/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900

